version: '3.8'

services:
  app:
    build: .
    container_name: kara_data_app
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8000:8000"  # for FastAPI

  db:
    image: postgres:15
    container_name: kara_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
